version: "2"
services:
  app:
    image: golang:1.16
    volumes:
     - ..:/go/src/app
    working_dir: /go/src/app
    command: bash -c "ls -l && go mod vendor && go build . && ./discordgoblindtest"
